### ISSUE TITLE
Prevent images from overflowing provided space on forums and match comms

### ISSUE THREAD

**Issue by AndKenneth** [ozfortress/citadel#104]
A few options I can think of:

- Restrict the size of embedded images (show error)
- Automatically rehost large images at a smaller size
- Dynamically resize the image using styling/css
- Change embed to a link when it's over a certain size.

**Comment by BenjaminSchaaf** [comment]
Currently the only images we host are avatars. Forum image hosting is a possible future feature. The only real solution is some css to limit image size.

**Comment by BenjaminSchaaf** [comment]
Example: https://warzone.ozfortress.com/leagues/1/matches/175

**Comment by BenjaminSchaaf** [comment]
Fixed as of e0c2c14a4aa8de797a661dc8bc52f3cbaf09309e
