### ISSUE TITLE
Points table should show all factors that calculate table positioning.

### ISSUE THREAD

**Issue by AndKenneth** [ozfortress/citadel#105]
![image](https://cloud.githubusercontent.com/assets/5133959/18420611/b6301cb8-78ca-11e6-80c8-237b891a9222.png)

This should be a table more similar to this, so everyone can see exactly where they stand on all areas.

![image](https://cloud.githubusercontent.com/assets/5133959/18420624/e0968000-78ca-11e6-8b5d-02617abc8626.png)

**Comment by BenjaminSchaaf** [comment]
Do we want to display all statistics available to us, or only those that we use for tiebreaking?

CC @obla

**Comment by obla** [comment]
Not all columns are needed. What are your thoughts?

**Comment by BenjaminSchaaf** [comment]
Showing all tiebreaking statistics makes it easy to see why a team's rank is what it is, but on the other hand, showing stuff like losses and byes might be a little useful. Doing both is really awkward, since the data kinda overlaps...

**Comment by obla** [comment]
What columns would you take?

**Comment by BenjaminSchaaf** [comment]
Score, Byes and set W-L-T are the trivial ones.

**Comment by BenjaminSchaaf** [comment]
I've just made it tiebreaker statistics for now. I'll leave this open in case we want anything else

**Comment by BenjaminSchaaf** [comment]
Closing this now, my change seems to be fine.
