### ISSUE TITLE
Current "Swiss" system implements Monrad pairing, not swiss

### ISSUE THREAD

**Issue by AndKenneth** [ozfortress/citadel#106]
Based on review of https://github.com/ozfortress/citadel/blob/master/lib/match_seeder/swiss.rb

**Comment by BenjaminSchaaf** [comment]
'Swiss' pairing isn't a thing AFAIK. There's Swiss tournament, and then different kinds of pairing systems. Dutch and Monrad are popularly used pairing systems.

**Comment by BenjaminSchaaf** [comment]
> obla [10:50 PM]  
i think what works now is fine
