### ISSUE TITLE
Availability Locking

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#112]
Saturday 8PM to Sunday 4PM

**Comment by BenjaminSchaaf** [comment]
Won't be time based, but a option similar to `Roster locked` for a league.

**Comment by AndKenneth** [comment]
Manually done? Could possibly cook up a simple script which automated this over the course of the tournament.

**Comment by BenjaminSchaaf** [comment]
Sure, a script could do it. But not a feature in citadel yet

**Comment by BenjaminSchaaf** [comment]
Implemented schedule locking
