### ISSUE TITLE
Fix sorting of rosters for disbanded rosters

### ISSUE THREAD

**Issue by BenjaminSchaaf** [ozfortress/citadel#119]
Put disbanded rosters at the bottom

**Comment by abender777** [comment]
Looks like the disbanded rosters can still appear above some non disbanded rosters if they have 0 points also? 

![image](https://user-images.githubusercontent.com/843190/36352133-7f3db540-1508-11e8-92df-66bda2b7cc5a.png)

**Comment by BenjaminSchaaf** [comment]
Good catch @abender777

**Comment by abender777** [comment]
So just wondering about github best practice, was it ok to reply here, or should I have created a new issue referencing it?

**Comment by BenjaminSchaaf** [comment]
Either is fine. In this case it was a regression, a bug in the fix for this issue, so here is appropriate. In almost every case a new issue works just as well, including this case.
