### ISSUE TITLE
Scores pending when generating rounds sometimes

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#129]

**Comment by BenjaminSchaaf** [comment]
Have you got an example of inputs where it's happened?

**Comment by obla** [comment]
http://i.imgur.com/SyYerSH.png

Result: Can't edit rounds unless scores are pending

**Comment by BenjaminSchaaf** [comment]
So, BYE matches automatically confirm themselves, but if there's an error when creating a match it doesn't reset this. Since the same display logic is used for creating and editing matches, creating an invalid BYE match results in sets no longer being editable.
