### ISSUE TITLE
Automated toggle for schedule locking

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#131]
Captains may change their team’s availability from a week to week basis from Thursday 4:00PM to Saturday 8:00PM.

**Comment by obla** [comment]
Can this be made priority?

**Comment by BenjaminSchaaf** [comment]
Is it good enough to just throw it up as a cron job?

**Comment by obla** [comment]
Yes.

**Comment by BenjaminSchaaf** [comment]
k done. We'll see how well it works
