### ISSUE TITLE
Last remaining captain can transfer out of team

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#138]
Leaves team with no captain

**Comment by BenjaminSchaaf** [comment]
Transferring out doesn't remove/change any permissions

**Comment by obla** [comment]
But leaves league roster with no captain

**Comment by BenjaminSchaaf** [comment]
The captain in general can just not transfer to the roster though.

**Comment by obla** [comment]
Have at least one captain in a league roster.

**Comment by BenjaminSchaaf** [comment]
A nicer way of handling this might be to display captain tags for transfer requests.
Any team that's transferring a captain out needs to be looked into anyway.
Thoughts @obla ?

**Comment by obla** [comment]
Sorry for delay, good call. With the way it works now, perhaps like highlighted text around player (if captain)?
