### ISSUE TITLE
Inconsistent display of team name when team name changed/updated

### ISSUE THREAD

**Issue by wackychocolatefactory** [ozfortress/citadel#155]
There are inconsistencies when a team name is changed or updated. 

Some sections of the site still display the old team name:
- League table
- Team page > x is currently playing
- Team page > match history
- Matches, Matches > comments

It makes sense that team name for match history and old comments contain the old team name as that was the team name when those entries were created.

![image](https://cloud.githubusercontent.com/assets/20605661/20658314/ee6da2c4-b58f-11e6-9e58-26104d72f22f.png)

**Comment by BenjaminSchaaf** [comment]
That's by design. If a team played a season as X, it should always stay as X. This allows people to see the history of a team's name.
