### ISSUE TITLE
If no maps are set when generating a single match, they get marked as Confirmed

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#156]
Not sure if this is the same when generating rounds.

**Comment by BenjaminSchaaf** [comment]
Can't reproduce, was the match actually confirmed after creation?

**Comment by obla** [comment]
On second thought it was a TEAM X vs BYE.

**Comment by BenjaminSchaaf** [comment]
so issue closed?

**Comment by obla** [comment]
Yes
