### ISSUE TITLE
Add limit to descriptions to prevent image flooding

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#166]

**Comment by BenjaminSchaaf** [comment]
Example?

Since images are just markdown, preventing image spam isn't really possible without massively restricting text. A simpler solution might just be stricter rules for descriptions/tighter administration.

**Comment by BenjaminSchaaf** [comment]
Thoughts @obla ?

**Comment by obla** [comment]
I'm leaning towards text in this situation. Character limit? It's meant to be a description, not a flood of images.

**Comment by BenjaminSchaaf** [comment]
```
We're a new team looking to have fun this season. Blah blah blah, new players, blah blah blah open, blah blah blah other stuff, etc. and so on.
```
vs
```
![](goo.gl/JgkUGC) ![](goo.gl/JgkUGC) ![](goo.gl/JgkUGC) ![](goo.gl/JgkUGC) ![](goo.gl/JgkUGC) ![](goo.gl/JgkUGC) ![](goo.gl/JgkUGC)
```

Approximately the same length, one is a very short description. The other is a flood of images.

**Comment by obla** [comment]
500 character limit

**Comment by BenjaminSchaaf** [comment]
I've limited it to 1000, to allow space for quoting

**Comment by obla** [comment]
Thank you.
