### ISSUE TITLE
Allow linking Discord to Citadel profile

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#170]
"The player must be registered on the [ozfortress Discord server.](https://discord.gg/0Scfe0bjjACAuRJ0)"

e.g. "Player#12345"

**Comment by BenjaminSchaaf** [comment]
Are you planning on making this a hard requirement?

**Comment by obla** [comment]
I want to! Your thoughts?

**Comment by obla** [comment]
Resolved after discussion. Discord ID not necessary in Citadel.
