### ISSUE TITLE
Match order is reversed

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#184]
![image](https://cloud.githubusercontent.com/assets/8676914/23162776/b8f8243e-f883-11e6-9625-da67135e6b5c.png)

**Comment by BenjaminSchaaf** [comment]
I mean, the order is right when you consider the latest matches being on top...

**Comment by obla** [comment]
It just kinda reads wrong. Maybe gather thoughts with other people?

**Comment by BenjaminSchaaf** [comment]
I could reverse the order just for upcoming matches

**Comment by obla** [comment]
Yes
