### ISSUE TITLE
Add numbering to points table titles to show determining of ranking

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#189]
ie.

1. Points
2. Tied wins

etc.

**Comment by BenjaminSchaaf** [comment]
Is this really needed? It makes the table harder to read on mobile devices.

**Comment by obla** [comment]
Then no, was just grabbing inspiration from Challonge.

**Comment by BenjaminSchaaf** [comment]
http://pasteboard.co/CsDT647SR.png vs http://pasteboard.co/CsEbJCbev.png

**Comment by obla** [comment]
Not too fussed either way, your call.

**Comment by BenjaminSchaaf** [comment]
Lets stick to without numbering.
