### ISSUE TITLE
Add back SteamID32

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#195]
Happy to discuss this. SteamID32 is still used in so many things and would make it so much easier.

**Comment by BenjaminSchaaf** [comment]
TF2 doesn't use it anymore though...

**Comment by obla** [comment]
I use it for medals and IP tracking

**Comment by BenjaminSchaaf** [comment]
convert it then. Unless there's some service which we really need it makes more sense to match what tf2 uses.

**Comment by obla** [comment]
Ok
