### ISSUE TITLE
Steam ID Link -  made more obvious

### ISSUE THREAD

**Issue by yauchh** [ozfortress/citadel#199]
Either make more prominent on the screen or use a steam logo icon for the link/ next to the link etc.

**Comment by BenjaminSchaaf** [comment]
http://pasteboard.co/JvQ5O3SzY.png Maybe just adding the standard link icon to it would be better?

**Comment by BenjaminSchaaf** [comment]
cc @obla

**Comment by obla** [comment]
Either way works.
