### ISSUE TITLE
Verify rosters link is visible when not logged in or results approved

### ISSUE THREAD

**Issue by Wiethoofd** [ozfortress/citadel#205]
I doubt non-admin or regular viewers (i.e. not logged in) of match pages (/matches) need to see the 'verify.ozfortress.com' link (the one that checks console output against the team rosters of a given match link or ID).

Link doesn't really have to be visible when:
- Not logged in
- Logged in and not on the roster
- Not admin
- Results have been verified/approved

**Comment by BenjaminSchaaf** [comment]
Its useful for casters, who might not be admins or on the roster. I just think its easier to keep it open to everyone.

**Comment by Wiethoofd** [comment]
At least removing it when the match results have been approved would make some sense.

Also casters/camera can't get status from the servers without rcon.

And having *Verify Rosters* as text instead of the url displayed could be useful. (I was confused before I clicked the link, thinking it was something to verify the results)

**Comment by BenjaminSchaaf** [comment]
Maybe a tooltip would be better, since verify rosters seems just as vague?
