### ISSUE TITLE
Direct links to match page comments

### ISSUE THREAD

**Issue by Wiethoofd** [ozfortress/citadel#206]
Match Page comments have an ID and a time stamp, but can't be directly linked to.

Suggesting to add a `href="#comm_#{comm.id}"` (match comment ID from [line 7](https://github.com/ozfortress/citadel/blob/485e7bf2c95ff5c20c4276692e422d2e2f542db7/app/views/leagues/matches/comms/_comm.html.haml#L7)) link to the [time of the post](https://github.com/ozfortress/citadel/blob/485e7bf2c95ff5c20c4276692e422d2e2f542db7/app/views/leagues/matches/comms/_comm.html.haml#L13-L14).

**Comment by BenjaminSchaaf** [comment]
Great idea!
