### ISSUE TITLE
[API] SteamID64 missing quotes causing issues with json_decode

### ISSUE THREAD

**Issue by Wiethoofd** [ozfortress/citadel#207]
Fetching the JSON of a user object containing a SteamID64 (in matches, users, rosters) and decoding the returned data with PHP incorrectly converts the 64-bit int. Similar things should happen when using javascript to handle the data.

Adding quotes around the ID should prevent the ids from being converted incorrectly.

**Comment by BenjaminSchaaf** [comment]
I'll add a `steam_64_str` that uses a string representation. Some JSON implementations aren't stupid.
