### ISSUE TITLE
[API] Team avatars missing in response

### ISSUE THREAD

**Issue by Wiethoofd** [ozfortress/citadel#208]
Teams (can) have avatars set on their team pages, this is however not available in the API response for rosters (teams on warzone?) and the matches data.

**Comment by BenjaminSchaaf** [comment]
The issue is that teams have not been implemented in the API. rosters have been. Rosters are a list of users participating in a league, that is linked to a team. The team has the avatar, the roster doesn't. (Feel free to add an issue for implementing teams for the API)
