### ISSUE TITLE
Manage button for rosters gets cut off when there is a long roster name

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#220]
![image](https://cloud.githubusercontent.com/assets/8676914/25311507/20b1712e-2846-11e7-9db4-87bc9bb5bb1c.png)

**Comment by BenjaminSchaaf** [comment]
I think this is only an issue for admins, since normal users can't see `View Details`.
Currently the only thing the roster pages add for admins is the admin comments. We could instead move those to the manage page?

**Comment by obla** [comment]
Sure
