### ISSUE TITLE
On leagues page, separate by year

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#222]

**Comment by BenjaminSchaaf** [comment]
This seems a bit arbitrary, especially considering summer cup 1 2017 was actually in 2016.

**Comment by obla** [comment]
Helps sort things out a little. Is there another way of categorising? ozfortress season leagues and Other?

**Comment by BenjaminSchaaf** [comment]
Manual categorization for leagues is doable. Would that work?

**Comment by obla** [comment]
Into those two categories? Sure.

**Comment by BenjaminSchaaf** [comment]
I mean in general, add a category field to leagues or something.

**Comment by obla** [comment]
Sounds good to me. Do you have suggestions for the categories?

**Comment by BenjaminSchaaf** [comment]
For ozfortress I'd just say the standard league, summer cups and ultiduo tournaments

**Comment by obla** [comment]
Alright

**Comment by obla** [comment]
Is there a way to have them categorised by default instead of a dropdown selection?

**Comment by BenjaminSchaaf** [comment]
What do you mean?
