### ISSUE TITLE
History of transfers per league on admin transfers page

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#227]

**Comment by BenjaminSchaaf** [comment]
How do we want this to work? Show all transfers for everyone requesting a transfer?

**Comment by obla** [comment]
Or 'obla' accepted X's transfer from 1 to 2 on DATE.

**Comment by BenjaminSchaaf** [comment]
We don't track who accepted the transfer right now, do we want to do that?

**Comment by BenjaminSchaaf** [comment]
None the less I don't see how your suggestion is any different to mine?

**Comment by obla** [comment]
Would be nice if it's not too much work.

**Comment by obla** [comment]
Well then yes history of all requested transfers for that league. The 'or' in my comment is redundant.

**Comment by BenjaminSchaaf** [comment]
*All* previously requested transfers, including denied ones? That'll be a very cluttered page.

**Comment by obla** [comment]
Definitely denied ones. Some people ask why was my transfer denied and I want to be able to track that. I don't know how to declutter. By week?

**Comment by BenjaminSchaaf** [comment]
'Week' isn't really a solid concept.

**Comment by obla** [comment]
I'm ok sorting with time; any other suggestions?

**Comment by BenjaminSchaaf** [comment]
Can't think of any

**Comment by BenjaminSchaaf** [comment]
Duplicate of #213
