### ISSUE TITLE
Suggestion about the visualising bracket thingo

### ISSUE THREAD

**Issue by yauchh** [ozfortress/citadel#243]
When clicking on a branch of the visualised bracket magic tree thing, maybe have it redirect to the match page instead of the individual team pages? Just a thought.

**Comment by obla** [comment]
Click on the grey bit and it goes to the match page.

**Comment by BenjaminSchaaf** [comment]
Maybe there's a way to make that more obvious?

**Comment by BenjaminSchaaf** [comment]
Any suggestions?

**Comment by BenjaminSchaaf** [comment]
Since its been more than a week, I'll close this issue. If anyone has any ideas I'll reopen it.
