### ISSUE TITLE
Discord widget integration on sidebar or something of that sort

### ISSUE THREAD

**Issue by yauchh** [ozfortress/citadel#246]
Especially with forum activity going downhill it would be good to have the discord being very **front and bold and centre** to say this is where a lot of the discussion is - idk if such a thing exists but yeah X many people online and all that sorta stuff - purely because discord is 100% the new forums and we wanna direct traffic and discussion there.

**Comment by BenjaminSchaaf** [comment]
https://blog.discordapp.com/add-the-discord-widget-to-your-site-d45ffcd718c6

**Comment by BenjaminSchaaf** [comment]
"discord is the new forums", then what are the citadel forums for?

**Comment by yauchh** [comment]
i just mean in terms of activity and participation its moved to discord from the old website forums

**Comment by BenjaminSchaaf** [comment]
Pretty sure this is done ;)
