### ISSUE TITLE
Prevent players from leaving the player pool if there is an active transfer

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#271]
Don't know if this only pertains to transfers in. Thoughts?

**Comment by BenjaminSchaaf** [comment]
This is only checked for transfers in, its to give players leeway to prevent being transferred. Say a player accepts an invite, a transfer request is made, but the player changes his mind. He can just leave the team.

**Comment by obla** [comment]
Is there another way of allowing this change of mind?

**Comment by BenjaminSchaaf** [comment]
Without adding more UX complexity I don't really see how. Is this really much of an issue though, I'd say you need to investigate in these situations anyway?

**Comment by obla** [comment]
Is there a warning popup currently for leaving team?

**Comment by BenjaminSchaaf** [comment]
Yes: `Are you sure you want to leave this team?`

**Comment by obla** [comment]
Add an if for if there an active transfer?

`Are you sure you want to leave this team? This will remove the active pending transfer for you.`

or something along the lines of that

**Comment by BenjaminSchaaf** [comment]
Hm, thats the first time you've actually suggested a code change rather than a feature :)

Maybe something along the lines of `You are pending a transfer for {league} into this team. Are you sure you want to leave?`

**Comment by obla** [comment]
You mean, the first time I've been considerate?

Sure that works too.

**Comment by BenjaminSchaaf** [comment]
> Add an if for

Instead of "make it say this when"

**Comment by obla** [comment]
Ah yes, I used my brain this time.
