### ISSUE TITLE
Use <me> as a reference to your own user 

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#272]
ie https://warzone.ozfortress.com/users/3/edit goes to your own settings

This helps with the FAQ.

**Comment by BenjaminSchaaf** [comment]
Something like: `/profile`, `/profile/edit`?

Could make a redirect for those.

**Comment by obla** [comment]
Yeah like that but not profile. `me` or `my`?

**Comment by BenjaminSchaaf** [comment]
I really don't like those
