### ISSUE TITLE
List IPs on user profiles

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#276]
Possibly accounts with matching IPs as well.

**Comment by BenjaminSchaaf** [comment]
Listing matching IPs is a pretty expensive operation

**Comment by obla** [comment]
What if it wasn't displayed by default? `Click here to show IPs`

**Comment by BenjaminSchaaf** [comment]
Yea, thats an option. Maybe even a separate page will full information.

**Comment by obla** [comment]
Sure, either works. If we have a full page, what other information could it include other than IPs and potential alts? Make use of that space.

**Comment by BenjaminSchaaf** [comment]
recent visits? idk any other ideas?

**Comment by obla** [comment]
Have those two for now. Is location or geolocation a good idea?

**Comment by BenjaminSchaaf** [comment]
Maybe I can make it link to an external service. I'd rather not add expensive geolocation fetching directly to citadel
