### ISSUE TITLE
Disbands should make home/away forfeits, not mutual forfeits

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#280]

**Comment by BenjaminSchaaf** [comment]
Example please

**Comment by obla** [comment]
![image](https://user-images.githubusercontent.com/8676914/27827258-c3d4b212-60f9-11e7-9674-bbf84d7d291d.png)
https://warzone.ozfortress.com/teams/274

**Comment by BenjaminSchaaf** [comment]
I will download the backups and check how accurate these are. The system does make thing mutual forfeits if say: the home team forfeit that match and then the away team disbands, or both teams disband.

**Comment by BenjaminSchaaf** [comment]
I will download the backups and check how accurate these are. The system does make thing mutual forfeits if say: the home team forfeit that match and then the away team disbands, or both teams disband.
