### ISSUE TITLE
Public notes section for both rosters, teams and players

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#301]

**Comment by BenjaminSchaaf** [comment]
Doing rosters *and* teams makes things a little convoluted on the page.

**Comment by obla** [comment]
Rosters or teams then

What do you suggest?

**Comment by BenjaminSchaaf** [comment]
Actually, thats a good question. Each has its own advantages. I think I'll do both and ozfortress can use whichever.

**Comment by BenjaminSchaaf** [comment]
I can hide it when there isn't anything so as long as only one is used it won't be too bad
