### ISSUE TITLE
Forfeit option does not ask for confirmation

### ISSUE THREAD

**Issue by sageaus** [ozfortress/citadel#317]
According to brion he accidentally forfeited in a tired daze as their was no confirmation after hitting the forfeit button.

**Comment by BenjaminSchaaf** [comment]
Nope, there's definitely a confirmation dialogue on that: https://github.com/ozfortress/citadel/blob/d592a67b2c90e05a4a2b0e53603618fb95b905d3/app/views/leagues/matches/_match_scores.html.haml#L11
