### ISSUE TITLE
Confirmation popup when inputting/accepting forfeits

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#334]

**Comment by BenjaminSchaaf** [comment]
Is this for admins or regular users? Regular users [already have a confirmation dialog](https://github.com/ozfortress/citadel/blob/c7a9405c14da5a61f3f1d658e9a8d976a7e6afbd/app/views/leagues/matches/_match_scores.html.haml#L11)

**Comment by obla** [comment]
Ok thanks
