### ISSUE TITLE
Allow admins to sign up teams to leagues.

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#339]
Permissions needed to add teams to league etc.

**Comment by BenjaminSchaaf** [comment]
Whats usually the situation this is used for?

**Comment by obla** [comment]
When a member messes up somewhere and doesn't realise he's not signed up to the league due to a player being on another roster or just being a complete dingus.

**Comment by BenjaminSchaaf** [comment]
With #338, is this much of an issue? I just don't see why captains can't do the signups themselves, even under these conditions?

**Comment by obla** [comment]
No, with #338 we can close this.
