### ISSUE TITLE
Upcoming matches text should be made more understandable.

### ISSUE THREAD

**Issue by LuciusDev** [ozfortress/citadel#352]
![screenshot from 2018-02-14 22-29-07](https://user-images.githubusercontent.com/14645522/36196752-91e2bfcc-11d6-11e8-993f-1652fb79a15c.png)
Should read "Your team has no upcoming matches" for more clarity

**Comment by LuciusDev** [comment]
Heh. Need to learn how it works.

**Comment by LuciusDev** [comment]
It ended up with me being confused about how the matches were displayed when there weren't any for your team. We decided to add this as it was a little unclear since when there are no matches and you aren't logged in/not playing in that season or something like that. I edited the original post which had more screenshots and made more sense when I was confused. I fell it needs to give a more custom response here. The default when you aren't logged in or in the league is that it shows the upcomming top division matches.
If you have a look at my pull request you can see what we were trying to do. My citadel install is broken at the moment and I haven't had a chance to finish it so feel free to do something similar. https://github.com/ozfortress/citadel/pull/353

**Comment by BenjaminSchaaf** [comment]
Fixed by f79131bfaa127048e5e978c40415328f2501f56a
