### ISSUE TITLE
bug in notification after deferring

### ISSUE THREAD

**Issue by AndKenneth** [ozfortress/citadel#357]
![slack-imgs](https://user-images.githubusercontent.com/5133959/37823569-ba9d40a6-2eee-11e8-8466-a020ef203acc.png)

We deferred our first ban, causing this message to show. I think it's assuming that the other team is the one that deferred?

**Comment by LucasTeirlynck** [comment]
![image](https://user-images.githubusercontent.com/17379095/39956206-3797920a-55dc-11e8-9dc1-c759e5ae83c2.png)

Updated, now actively shows when map pick/ban 
#362
