### ISSUE TITLE
Calendar Integration

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#392]
Would be nice to have a calendar inbuilt.

**Comment by obla** [comment]
Google

**Comment by BenjaminSchaaf** [comment]
That doesn't really clear anything up?

**Comment by BenjaminSchaaf** [comment]
I know what you meant, but it doesn't clear anything up. Are you just suggesting embedding some calendar on certain pages, or actually integrating a calendar with how leagues function?

**Comment by coreobs** [comment]
Can do this with escaping, so will close for now.
