### ISSUE TITLE
"Has a distinct winner" is missing a message on failed validation

### ISSUE THREAD

**Issue by mkrl** [ozfortress/citadel#393]
If the amount of sets is even when generating a round with "Has a distinct winner" set to true, an error message should appear instead of just redirecting to the creation form again.

**Comment by BenjaminSchaaf** [comment]
I can't reproduce this. This isn't currently validated until match submission time.

**Comment by mkrl** [comment]
Yes, that's exactly what I meant. 
LGTM, thanks
