### ISSUE TITLE
Round number can be blank

### ISSUE THREAD

**Issue by mkrl** [ozfortress/citadel#400]
When the round number is blank and the league is running, an error occurs while rendering bracket data.

**Comment by BenjaminSchaaf** [comment]
That's not good...

**Comment by mkrl** [comment]
Actually I have already fixed that that's one line change (not including tests), can make a PR later
https://github.com/match-tf/citadel/commit/1bf42ac2d0fdf8fadd1a7dca7b487a25d821a7fa

**Comment by BenjaminSchaaf** [comment]
I'll just chuck that fix into master, not worth a pr

**Comment by BenjaminSchaaf** [comment]
Thanks for sorting this one out @mkrl :)
