### ISSUE TITLE
Past rosters without matches cause team page to throw 500

### ISSUE THREAD

**Issue by mkrl** [ozfortress/citadel#430]
When a team has a roster but no matches in a league that was marked as completed, team page is throwing an error trying to render `_matches_table`.

### Steps to reproduce

1. Sign a team up for a league
2. Do not create any matches / purge all team matches
3. Mark the league as completed
4. Access team page

### Suggested fix
`app/views/teams/show.html.haml:180`
```
...

          - unless matches.nil?
            .panel-default
              .panel-heading
                Matches:
              = render 'leagues/matches/matches_table', matches: matches, roster: roster

...
```

Obviously, very unlikely to happen, but it happened. Let me know if you would like a different approach.

**Comment by BenjaminSchaaf** [comment]
Nice catch, I'd use the exact same solution. Feel free to submit a pr
