### ISSUE TITLE
Transfer history should be ordered by date descending

### ISSUE THREAD

**Issue by IAmThermite** [ozfortress/citadel#435]
It is a tiny bit annoying when checking the transfer history to see if you allowed or denied a transfer recently. Is worse when it comes to the larger divisions when there are generally more transfers so lots of scrolling down occurs. I propose that the order is changed to most recent transfer first.

**Comment by IAmThermite** [comment]
Assuming this just a simple `Array.reverse` in `controllers/leagues/transfers_controller.rb#L54`?

**Comment by BenjaminSchaaf** [comment]
`Array.reverse` would be inadvisable. `created_at: :desc` is a better solution in [transfers_controller.rb](https://github.com/ozfortress/citadel/blob/master/app/controllers/leagues/transfers_controller.rb#L21).
