### ISSUE TITLE
Community rules redirect to normal rules

### ISSUE THREAD

**Issue by mitch-cl** [ozfortress/citadel#439]
community rules don't exist and just shows the league ruleset

**Comment by BenjaminSchaaf** [comment]
What's the issue here?

**Comment by mitch-cl** [comment]
https://github.com/ozfortress/citadel/commit/53f19daf02f3eadf06a2ba6f0f15e34ab118662f?diff=split

I don't know if this was intentional but if it was you should probably get rid of one of these 
![image](https://user-images.githubusercontent.com/21251983/63256972-23191f80-c2bc-11e9-85d6-c96f4e414918.png)
