### ISSUE TITLE
character limit

### ISSUE THREAD

**Issue by billw1** [ozfortress/citadel#440]
when you have a description with lots of formatting (images etc) you hit the 500 character limit very quickly. would be nice if it was much larger

**Comment by BenjaminSchaaf** [comment]
We've discussed it and it's gonna be a no. 500 is enough for a team description.

**Comment by billw1** [comment]
Any chance you could at least make it so formatting is not counted towards the limit? including images takes up a huge chunk since each character of the url is counted.
