### ISSUE TITLE
Steam browser login returns 500 error

### ISSUE THREAD

**Issue by coretf** [ozfortress/citadel#474]
"i use the steam overlay, i goto ozfort website, i click login with steam, i click logon on the steam web page, and then it says ' 500 Internal Server Error!
This is a bug, please report it to your administrator!'"

Login goes to a 500 on Steam overlay browsers, but other steam sites work fine.

**Comment by BenjaminSchaaf** [comment]
Fixed by 5621d278bc9ada555e766f1369dea226869de190
