### ISSUE TITLE
Rarely matches in swiss are not unique

### ISSUE THREAD

**Issue by BenjaminSchaaf** [ozfortress/citadel#51]
A non-issue outside of weird test data?

**Comment by AndKenneth** [comment]
https://github.com/ozfortress/citadel/blob/master/lib/match_seeder/swiss.rb#L43

This line appears to cause the bug.

**Comment by AndKenneth** [comment]
Closer look at the comments, this seems to be an intended feature?

**Comment by BenjaminSchaaf** [comment]
It's intended in the sense that I haven't found/looked deep into, a better solution.

**Comment by BenjaminSchaaf** [comment]
This is a side-effect of using monrad pairing, which isn't going to change
