### ISSUE TITLE
Multi line fixed width markdown is not respected

### ISSUE THREAD

**Issue by AndKenneth** [ozfortress/citadel#71]
Currently if you use triple back ticks to enclose a multi-line fixed width block of text, it will still only show up on one line. These would be the best way to show chatlogs.

**Comment by BenjaminSchaaf** [comment]
Hmm, this seems to be an issue with the markdown gem (redcarpet)

**Comment by BenjaminSchaaf** [comment]
Fixed as of 3e4085446e96e859a8157cd8abd8f4e998d4f47c
