### ISSUE TITLE
Batch notifications

### ISSUE THREAD

**Issue by BenjaminSchaaf** [ozfortress/citadel#92]
No clear plan for solving this yet

**Comment by BenjaminSchaaf** [comment]
This doesn't actually make any sense

**Comment by obla** [comment]
Which part?

**Comment by BenjaminSchaaf** [comment]
Which notifications would be batched?

**Comment by obla** [comment]
New matches, players? Regardless, it's pretty worthless I reckon.

**Comment by BenjaminSchaaf** [comment]
New matches have different links, so batching those doesn't make sense for that. I just think its better UX if there's a straight notification for everything

**Comment by obla** [comment]
Yeah fair, ticket to stay closed.
